// Liste complète des métiers d'artisans (ordre alphabétique)
export const PROFESSIONS = [
  "Agenceur d'intérieur",
  "Aménageur extérieur",
  "Arboriste",
  "Artisan cuir",
  "Artisan upcycling",
  "Bijoutier",
  "Brodeur",
  "Carreleur",
  "Carrossier",
  "Céramiste",
  "Coffreur",
  "Constructeur de maisons",
  "Constructeur ossature bois",
  "Cordonnier",
  "Coutelier",
  "Couturier indépendant",
  "Créateur en bois",
  "Créateur en métal",
  "Débosselage sans peinture",
  "Débroussailleur",
  "Dépanneur électroménager",
  "Dératisation",
  "Désinsectisation",
  "Ébéniste",
  "Électricien auto",
  "Électricien bâtiment",
  "Électricien IRVE",
  "Élagueur",
  "Fabricant de luminaires artisanaux",
  "Fabricant d'articles textiles sur mesure",
  "Fabricant de meubles sur mesure",
  "Ferronnier",
  "Ferronnier d'art",
  "Forgeron",
  "Graveur",
  "Graphiste artisanal",
  "Horloger",
  "Installateur de cuisines",
  "Installateur domotique",
  "Installateur portes de garage",
  "Installateur portails",
  "Installateur sanitaire",
  "Installateur VMC",
  "Installateur volets roulants",
  "Jardinier",
  "Joaillier",
  "Luthier",
  "Maçon",
  "Maroquinier",
  "Menuisier aluminium",
  "Menuisier bois",
  "Menuisier PVC",
  "Menuisier sur mesure",
  "Mécanicien auto",
  "Mécanicien moto",
  "Métallier",
  "Modéliste",
  "Peintre automobile",
  "Peintre bâtiment",
  "Photographe indépendant",
  "Plaquiste",
  "Plâtrier",
  "Plombier",
  "Potier",
  "Ramonage",
  "Restaurateur d'art",
  "Retoucheur",
  "Réparateur cycles",
  "Réparateur électronique",
  "Réparateur informatique",
  "Réparateur instruments de musique",
  "Réparateur machines agricoles",
  "Réparateur motos",
  "Réparateur sellerie auto",
  "Sellier automobile",
  "Sellier maroquinerie",
  "Sculpteur",
  "Sculpteur sur bois",
  "Serrurier",
  "Serrurier-dépanneur",
  "Solier-moquettiste",
  "Soudeur",
  "Soudeur artisanal",
  "Staffeur-ornemaniste",
  "Tapissier d'ameublement",
  "Tapissier mural",
  "Technicien pompes à chaleur",
  "Terrassier",
  "Tisserand",
  "Tourneur sur bois",
  "Verrier",
  "Vidéaste indépendant",
  "Vitrier",
  "Vitrier dépanneur",
  "Zingueur",
  "Autre" // Toujours en dernier
];
